# xxl-job
xxl:
  job:
    accessToken:
    admin:
      addresses: http://darren1112.com:14007/xxl-job-admin
    executor:
      appname: ${spring.application.name}
      ip:
      logpath: /tmp/ulearning-logs/xxl-job/${spring.application.name}
      logretentiondays: 30
      port: 24004