#jwt
jwt:
  header-token: Authorization-token
  header-refresh-token: Authorization-refresh-token
  secret: glFHrX0x5wYaDfhMMusyEg7p9ZVmz1hWgp1sKx0woVeLECAIn50VsHtOXf9b8fwK
  # token 过期时间 5分钟
  token: 300000
  # refresh-token 过期时间7天
  refresh-token: 604800000

#swagger2
swagger:
  enabled: true