info:
  build:
    name: @project.name@
    description: @project.description@
    artifactId: @project.artifactId@
    version: @project.version@
#服务器配置
server:
  port: 14004
  jetty:
    accesslog:
      enabled: true
      filename: ./ulearning-logs/${spring.application.name}/jetty/access/${spring.application.name}.yyyy-MM-dd.log
      file-date-format: .yyyy-MM-dd
      retention-period: 20
      append: true
      extended-format: true
      locale: zh_CN
      time-zone: GMT+8
      log-cookies: false
      log-server: true
      log-latency: true

    max-http-form-post-size: 4MB
    acceptors: 16
    selectors: 16

  servlet:
    context-path: /${spring.application.name}
#日志配置
logging:
  config: classpath:config/local/logback.xml
#监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    threaddump:
      enabled: false