info:
  build:
    name: @project.name@
    description: @project.description@
    artifactId: @project.artifactId@
    version: @project.version@

server:
  port: 14001
  tomcat:
    basedir: /tmp/ulearning-logs/${spring.application.name}/tomcat
    accesslog:
      enabled: true
      directory: ./access
      buffered: false
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s %b %D %{User-Agent}i'
      prefix: ${spring.application.name}
      rotate: true
      suffix: .log

# 账号密码
spring:
  security:
    user:
      name: ENC(mRN97UhK2D6PTcXIdLhvdwxduCpXn1YF)
      password: ENC(orrD1ow1NHp+dB7PMJX03GTtKSb1wElV)

eureka:
  #关闭自我保护机制-开发环境开启
  server:
    enable-self-preservation: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

logging:
  config: classpath:config/prod/logback.xml

#监控配置
management:
  health:
    redis:
      enabled: false
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
