info:
  build:
    name: @project.name@
    description: @project.description@
    artifactId: @project.artifactId@
    version: @project.version@

### web
server:
  port: 8082
  tomcat:
    basedir: ./ulearning-logs/${spring.application.name}/tomcat
    accesslog:
      enabled: true
      directory: ./access
      buffered: false
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s %b %D %{User-Agent}i'
      prefix: ${spring.application.name}
      rotate: true
      suffix: .log
  servlet:
    context-path: /${spring.application.name}
#日志配置
logging:
  config: classpath:config/local/logback.xml
  file: ./ulearning-logs/${spring.application.name}/sys/info.${spring.application.name}.log
### actuator
management:
  health:
    # 关闭redis检测
    redis:
      enabled: false
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
### resources
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  ### freemarker
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
## xxl-job, triggerpool max size
xxl:
  job:
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30
    i18n:
    accessToken: