# xxl-job
xxl:
  job:
    accessToken:
    admin:
      addresses: http://10.66.2.81:14007/xxl-job-admin
    executor:
      appname: ${spring.application.name}
      # 双网卡时需要指定可通信ip
      ip: 10.66.2.81
      logpath: /tmp/ulearning-logs/xxl-job/${spring.application.name}
      logretentiondays: 30
      port: 24004
