# spring公共配置
spring:
  servlet:
    # 文件大小限制
    multipart:
      enabled: true
      #设置单个文件最大长度
      max-file-size: 600MB
      #最大请求文件的大小
      max-request-size: 600MB
  mail:
    username: ludaye1112@163.com
    password: luyuhao2010
    host: smtp.163.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            fallback: false
            class: javax.net.ssl.SSLSocketFactory
            port: 465
    port: 465
#jwt
jwt:
  header-token: Authorization-token
  header-refresh-token: Authorization-refresh-token
  secret: RxaM3fZtzFSEj02WlM7pjfUkUoedD561p54uZ4u3OR1R9KqpsEuthgFMEnG4zH9B
  # token 过期时间 5分钟
  token: 300000
  # refresh-token 过期时间2天
  refresh-token: 172800000

#swagger2
swagger:
  enabled: true

#fastDFS
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  #nginx访问地址
  reqHost: 47.95.14.126
  #nginx访问端口
  reqPort: 8888
  #TrackerList参数,支持多个
  tracker-list:
    - 47.95.14.126:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 500
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    max_idle_per_key: 5

#系统变量
ulearning:
  # 显示的学期前n年和后n年
  term:
    preyears: 1
    nextyears: 3
  file:
    # 默认MB
    # 图片最大限制
    photo-max-size: 5
    # 通告附件最大限制
    notice-attachment-max-size: 10
    # 实验附件最大限制
    experiment-attachment-max-size: 100
  # 日志配置
  log:
    # u_log表日志保留天数(包含当日且>=7)
    retention-days: 15
    # 最大清理天数
    max-delete-days: 100
  # 系统相关变量
  system:
    # 是否是开发模式，发布模式需要关闭
    dev-mode: false
    # 项目发布地址前缀
    suffix: /server
    # 系统模块映射
    module-map: "{1: '后台管理系统', 2: '监控系统', 3: '教师端', 4: '学生端'}"
