rocketmq:
  isEnable: false
  #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
  groupName: ${spring.application.name}
  #mq的nameserver地址
  namesrvAddr: ENC(f8ee7n299wY9XW5wJutOplctvCYzCuUw)
  #关闭vip通道，不使用10909端口
  vipChannelEnabled: false
  #producer
  producer:
    #消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    #发送消息超时时间,默认3000
    sendMsgTimeout: 5000
    #发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
  #consumer
  consumer:
    consumeThreadMin: 20
    consumeThreadMax: 64
