info:
  app:
    name: ${spring.application.name}
  build:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
#服务器配置
server:
  port: 14003
  tomcat:
    basedir: ./ulearning-logs/${spring.application.name}/tomcat
    accesslog:
      enabled: true
      directory: ./access
      buffered: false
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: ${spring.application.name}
      rotate: true
      suffix: .log
#日志配置
logging:
  config: classpath:config/local/logback.xml
# 数据源配置
spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.15.75.204:3306/ulearning_dev?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: daye1112
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      #      aop-patterns: com.ky.zstu.service.*


      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false

# mybatis配置
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml