info:
  build:
    name: @project.name@
    description: @project.description@
    artifactId: @project.artifactId@
    version: @project.version@
#服务器配置
server:
  port: 14003
  tomcat:
    basedir: ./ulearning-logs/${spring.application.name}/tomcat
    accesslog:
      enabled: true
      directory: ./access
      buffered: false
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: ${spring.application.name}
      rotate: true
      suffix: .log
  servlet:
    context-path: /system-manage
#日志配置
logging:
  config: classpath:config/local/logback.xml