#jwt
jwt:
  header-token: Authorization-token
  header-refresh-token: Authorization-refresh-token
  secret: i8JFlOtaWhPPmGj3EjrXj55e
  # token 过期时间 5分钟
  token: 300000
  # refresh-token 过期时间7天
  refresh-token: 604800000

#swagger2
swagger:
  enabled: true

#系统变量
ulearning:
  # 显示的学期前n年和后n年
  term:
    preyears: 3
    nextyears: 3