#路由配置
zuul:
  routes:
    gateway:
      path: /gateway/**
      stripPrefix: true
      serviceId: ulearning-gateway
    monitor:
      path: /monitor/**
      stripPrefix: false
      serviceId: ulearning-monitor
    system-manage:
      path: /system-manage/**
      stripPrefix: false
      serviceId: ulearning-system-manage

#jwt
jwt:
  header-token: Authorization-token
  header-refresh-token: Authorization-refresh-token
  secret: i8JFlOtaWhPPmGj3EjrXj55e
  # token 过期时间 5分钟
  token: 300000
  # refresh-token 过期时间7天
  refresh-token: 604800000